# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.send_invoice_request_guia_remision_inner import SendInvoiceRequestGuiaRemisionInner

class TestSendInvoiceRequestGuiaRemisionInner(unittest.TestCase):
    """SendInvoiceRequestGuiaRemisionInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendInvoiceRequestGuiaRemisionInner:
        """Test SendInvoiceRequestGuiaRemisionInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendInvoiceRequestGuiaRemisionInner`
        """
        model = SendInvoiceRequestGuiaRemisionInner()
        if include_optional:
            return SendInvoiceRequestGuiaRemisionInner(
                tipo_doc = '09',
                nro_doc = 'A8Q6-288'
            )
        else:
            return SendInvoiceRequestGuiaRemisionInner(
                nro_doc = 'A8Q6-288',
        )
        """

    def testSendInvoiceRequestGuiaRemisionInner(self):
        """Test SendInvoiceRequestGuiaRemisionInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
