# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.reconcile_document200_response import ReconcileDocument200Response

class TestReconcileDocument200Response(unittest.TestCase):
    """ReconcileDocument200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReconcileDocument200Response:
        """Test ReconcileDocument200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReconcileDocument200Response`
        """
        model = ReconcileDocument200Response()
        if include_optional:
            return ReconcileDocument200Response(
                success = True,
                message = '',
                estado = '',
                codigo = ''
            )
        else:
            return ReconcileDocument200Response(
                success = True,
                message = '',
        )
        """

    def testReconcileDocument200Response(self):
        """Test ReconcileDocument200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
