# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.api_v1_despatch_send_post_request_indicadores import ApiV1DespatchSendPostRequestIndicadores

class TestApiV1DespatchSendPostRequestIndicadores(unittest.TestCase):
    """ApiV1DespatchSendPostRequestIndicadores unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1DespatchSendPostRequestIndicadores:
        """Test ApiV1DespatchSendPostRequestIndicadores
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1DespatchSendPostRequestIndicadores`
        """
        model = ApiV1DespatchSendPostRequestIndicadores()
        if include_optional:
            return ApiV1DespatchSendPostRequestIndicadores(
                transbordo_programado = True,
                vehiculo_m1_l = True,
                retorno_vehiculo_envase_vacio = True,
                retorno_vehiculo_vacio = True,
                traslado_total_dam_ds = True,
                registro_transportista = True,
                traslado_contenedor_manifiesto = True
            )
        else:
            return ApiV1DespatchSendPostRequestIndicadores(
        )
        """

    def testApiV1DespatchSendPostRequestIndicadores(self):
        """Test ApiV1DespatchSendPostRequestIndicadores"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
