# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.send_invoice_request_detraccion import SendInvoiceRequestDetraccion

class TestSendInvoiceRequestDetraccion(unittest.TestCase):
    """SendInvoiceRequestDetraccion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendInvoiceRequestDetraccion:
        """Test SendInvoiceRequestDetraccion
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendInvoiceRequestDetraccion`
        """
        model = SendInvoiceRequestDetraccion()
        if include_optional:
            return SendInvoiceRequestDetraccion(
                cod_bien_servicio = '048',
                cuenta_banco = '0',
                porcentaje = 0,
                monto = 0,
                medio_pago = '001'
            )
        else:
            return SendInvoiceRequestDetraccion(
                cod_bien_servicio = '048',
                cuenta_banco = '0',
                porcentaje = 0,
                monto = 0,
        )
        """

    def testSendInvoiceRequestDetraccion(self):
        """Test SendInvoiceRequestDetraccion"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
