# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.api_v1_note_compute_post_request_items_inner import ApiV1NoteComputePostRequestItemsInner

class TestApiV1NoteComputePostRequestItemsInner(unittest.TestCase):
    """ApiV1NoteComputePostRequestItemsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1NoteComputePostRequestItemsInner:
        """Test ApiV1NoteComputePostRequestItemsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1NoteComputePostRequestItemsInner`
        """
        model = ApiV1NoteComputePostRequestItemsInner()
        if include_optional:
            return ApiV1NoteComputePostRequestItemsInner(
                descripcion = '0',
                cantidad = 0,
                valor_unitario = 0,
                unidad = '0',
                cod_producto = '',
                afectacion = '10',
                igv_porcentaje = 0,
                descuento = intifact_sdk.models._api_v1_invoice_compute_post_request_items_inner_descuento._api_v1_invoice_compute_post_request_items_inner_descuento(
                    porcentaje = 0, 
                    monto = 0, ),
                factor_icbper = 0,
                marca = '',
                cod_prod_sunat = ''
            )
        else:
            return ApiV1NoteComputePostRequestItemsInner(
                descripcion = '0',
                cantidad = 0,
                valor_unitario = 0,
        )
        """

    def testApiV1NoteComputePostRequestItemsInner(self):
        """Test ApiV1NoteComputePostRequestItemsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
