# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.api.company_api import CompanyApi


class TestCompanyApi(unittest.TestCase):
    """CompanyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CompanyApi()

    def tearDown(self) -> None:
        pass

    def test_claim_company(self) -> None:
        """Test case for claim_company

        Reclamar un RUC registrado por otra cuenta, con su certificado
        """
        pass

    def test_create_company(self) -> None:
        """Test case for create_company

        Crear empresa emisora
        """
        pass

    def test_get_company(self) -> None:
        """Test case for get_company

        Detalle de empresa
        """
        pass

    def test_get_company_logo(self) -> None:
        """Test case for get_company_logo

        Obtener logo de la empresa (PNG/JPG)
        """
        pass

    def test_list_companies(self) -> None:
        """Test case for list_companies

        Listar empresas emisoras
        """
        pass

    def test_update_company(self) -> None:
        """Test case for update_company

        Actualizar empresa
        """
        pass


if __name__ == '__main__':
    unittest.main()
