# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.api_v1_invoice_send_post400_response import ApiV1InvoiceSendPost400Response

class TestApiV1InvoiceSendPost400Response(unittest.TestCase):
    """ApiV1InvoiceSendPost400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1InvoiceSendPost400Response:
        """Test ApiV1InvoiceSendPost400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1InvoiceSendPost400Response`
        """
        model = ApiV1InvoiceSendPost400Response()
        if include_optional:
            return ApiV1InvoiceSendPost400Response(
                success = True,
                message = '',
                code = '',
                errors = [
                    intifact_sdk.models._api_v1_invoice_send_post_400_response_errors_inner._api_v1_invoice_send_post_400_response_errors_inner(
                        path = '', 
                        message = '', )
                    ]
            )
        else:
            return ApiV1InvoiceSendPost400Response(
                success = True,
                message = '',
        )
        """

    def testApiV1InvoiceSendPost400Response(self):
        """Test ApiV1InvoiceSendPost400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
