# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.send_summary_request_items_inner import SendSummaryRequestItemsInner

class TestSendSummaryRequestItemsInner(unittest.TestCase):
    """SendSummaryRequestItemsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendSummaryRequestItemsInner:
        """Test SendSummaryRequestItemsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendSummaryRequestItemsInner`
        """
        model = SendSummaryRequestItemsInner()
        if include_optional:
            return SendSummaryRequestItemsInner(
                tipo_doc = '',
                serie = 'W8Q6',
                correlativo = '480728',
                cliente_tipo_doc = '',
                cliente_num_doc = '',
                estado_item = '1',
                tipo_moneda = 'PEN',
                monto_oper_gravadas = 1.337,
                monto_oper_exoneradas = 1.337,
                monto_oper_inafectas = 1.337,
                monto_oper_gratuitas = 1.337,
                monto_igv = 1.337,
                monto_isc = 1.337,
                monto_otros_cargos = 1.337,
                monto_total = 1.337
            )
        else:
            return SendSummaryRequestItemsInner(
                tipo_doc = '',
                serie = 'W8Q6',
                correlativo = '480728',
                cliente_tipo_doc = '',
                cliente_num_doc = '',
                estado_item = '1',
                monto_total = 1.337,
        )
        """

    def testSendSummaryRequestItemsInner(self):
        """Test SendSummaryRequestItemsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
