# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.api_v1_documents_id_retry_post202_response import ApiV1DocumentsIdRetryPost202Response

class TestApiV1DocumentsIdRetryPost202Response(unittest.TestCase):
    """ApiV1DocumentsIdRetryPost202Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1DocumentsIdRetryPost202Response:
        """Test ApiV1DocumentsIdRetryPost202Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1DocumentsIdRetryPost202Response`
        """
        model = ApiV1DocumentsIdRetryPost202Response()
        if include_optional:
            return ApiV1DocumentsIdRetryPost202Response(
                success = True,
                message = '',
                job_id = ''
            )
        else:
            return ApiV1DocumentsIdRetryPost202Response(
                success = True,
                message = '',
        )
        """

    def testApiV1DocumentsIdRetryPost202Response(self):
        """Test ApiV1DocumentsIdRetryPost202Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
