# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.api_v1_ticket_ticket_status_get202_response_cdr_response import ApiV1TicketTicketStatusGet202ResponseCdrResponse

class TestApiV1TicketTicketStatusGet202ResponseCdrResponse(unittest.TestCase):
    """ApiV1TicketTicketStatusGet202ResponseCdrResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1TicketTicketStatusGet202ResponseCdrResponse:
        """Test ApiV1TicketTicketStatusGet202ResponseCdrResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1TicketTicketStatusGet202ResponseCdrResponse`
        """
        model = ApiV1TicketTicketStatusGet202ResponseCdrResponse()
        if include_optional:
            return ApiV1TicketTicketStatusGet202ResponseCdrResponse(
                id = '',
                code = '',
                description = '',
                notes = [
                    ''
                    ]
            )
        else:
            return ApiV1TicketTicketStatusGet202ResponseCdrResponse(
                id = '',
                code = '',
                description = '',
                notes = [
                    ''
                    ],
        )
        """

    def testApiV1TicketTicketStatusGet202ResponseCdrResponse(self):
        """Test ApiV1TicketTicketStatusGet202ResponseCdrResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
