# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.api.invoice_api import InvoiceApi


class TestInvoiceApi(unittest.TestCase):
    """InvoiceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InvoiceApi()

    def tearDown(self) -> None:
        pass

    def test_compute_invoice(self) -> None:
        """Test case for compute_invoice

        Calcular importes (IGV, descuentos, totales) sin emitir
        """
        pass

    def test_get_invoice_cdr(self) -> None:
        """Test case for get_invoice_cdr

        Descargar CDR (constancia de SUNAT)
        """
        pass

    def test_get_invoice_pdf(self) -> None:
        """Test case for get_invoice_pdf

        Obtener PDF (A4 oficina, ticket 80mm o ticket 58mm POS)
        """
        pass

    def test_get_invoice_xml(self) -> None:
        """Test case for get_invoice_xml

        Descargar XML firmado
        """
        pass

    def test_send_invoice(self) -> None:
        """Test case for send_invoice

        Enviar factura (01) o boleta (03) a SUNAT
        """
        pass


if __name__ == '__main__':
    unittest.main()
