# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.send_voided_request import SendVoidedRequest

class TestSendVoidedRequest(unittest.TestCase):
    """SendVoidedRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendVoidedRequest:
        """Test SendVoidedRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendVoidedRequest`
        """
        model = SendVoidedRequest()
        if include_optional:
            return SendVoidedRequest(
                empresa_ruc = '012345678910',
                correlativo = '480728',
                fecha_emision = '',
                fecha_referencia = '',
                items = [
                    intifact_sdk.models.send_voided_request_items_inner.sendVoided_request_items_inner(
                        tipo_doc = '', 
                        serie = 'W8Q6', 
                        correlativo = '480728', 
                        motivo_baja = '0', )
                    ]
            )
        else:
            return SendVoidedRequest(
                empresa_ruc = '012345678910',
                correlativo = '480728',
                fecha_emision = '',
                fecha_referencia = '',
                items = [
                    intifact_sdk.models.send_voided_request_items_inner.sendVoided_request_items_inner(
                        tipo_doc = '', 
                        serie = 'W8Q6', 
                        correlativo = '480728', 
                        motivo_baja = '0', )
                    ],
        )
        """

    def testSendVoidedRequest(self):
        """Test SendVoidedRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
