# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.api_v1_webhooks_post_request import ApiV1WebhooksPostRequest

class TestApiV1WebhooksPostRequest(unittest.TestCase):
    """ApiV1WebhooksPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1WebhooksPostRequest:
        """Test ApiV1WebhooksPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1WebhooksPostRequest`
        """
        model = ApiV1WebhooksPostRequest()
        if include_optional:
            return ApiV1WebhooksPostRequest(
                empresa_ruc = '012345678910',
                tenant_id = 'ffffffff-ffff-ffff-ffff-ffffffffffff',
                url = '',
                events = [
                    'document.accepted'
                    ],
                description = '',
                secret = '0123456789101112131415'
            )
        else:
            return ApiV1WebhooksPostRequest(
                url = '',
                events = [
                    'document.accepted'
                    ],
        )
        """

    def testApiV1WebhooksPostRequest(self):
        """Test ApiV1WebhooksPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
