# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.api_v1_summary_send_post202_response import ApiV1SummarySendPost202Response

class TestApiV1SummarySendPost202Response(unittest.TestCase):
    """ApiV1SummarySendPost202Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1SummarySendPost202Response:
        """Test ApiV1SummarySendPost202Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1SummarySendPost202Response`
        """
        model = ApiV1SummarySendPost202Response()
        if include_optional:
            return ApiV1SummarySendPost202Response(
                success = True,
                message = '',
                data = intifact_sdk.models._api_v1_summary_send_post_202_response_data._api_v1_summary_send_post_202_response_data(
                    id = '', 
                    estado = '', 
                    ticket = '', 
                    hash = '', )
            )
        else:
            return ApiV1SummarySendPost202Response(
                success = True,
                message = '',
        )
        """

    def testApiV1SummarySendPost202Response(self):
        """Test ApiV1SummarySendPost202Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
