# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.api_v1_note_send_post_request_detalle_inner import ApiV1NoteSendPostRequestDetalleInner

class TestApiV1NoteSendPostRequestDetalleInner(unittest.TestCase):
    """ApiV1NoteSendPostRequestDetalleInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1NoteSendPostRequestDetalleInner:
        """Test ApiV1NoteSendPostRequestDetalleInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1NoteSendPostRequestDetalleInner`
        """
        model = ApiV1NoteSendPostRequestDetalleInner()
        if include_optional:
            return ApiV1NoteSendPostRequestDetalleInner(
                unidad = '0',
                cantidad = 0,
                cod_producto = '0',
                descripcion = '0',
                marca = '',
                monto_valor_unitario = 0,
                monto_base_igv = 0,
                porcentaje_igv = 0,
                igv = 0,
                tip_afe_igv = '10',
                total_impuestos = 0,
                monto_precio_unitario = 0,
                monto_valor_venta = 0,
                descuento = 0,
                descuento_item = 0,
                factor_icbper = 0,
                cod_prod_sunat = ''
            )
        else:
            return ApiV1NoteSendPostRequestDetalleInner(
                unidad = '0',
                cantidad = 0,
                cod_producto = '0',
                descripcion = '0',
                monto_valor_unitario = 0,
                monto_base_igv = 0,
                igv = 0,
                total_impuestos = 0,
                monto_precio_unitario = 0,
                monto_valor_venta = 0,
        )
        """

    def testApiV1NoteSendPostRequestDetalleInner(self):
        """Test ApiV1NoteSendPostRequestDetalleInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
