# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.api.plans_api import PlansApi


class TestPlansApi(unittest.TestCase):
    """PlansApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PlansApi()

    def tearDown(self) -> None:
        pass

    def test_api_v1_plans_get(self) -> None:
        """Test case for api_v1_plans_get

        Listar planes (solo master)
        """
        pass

    def test_api_v1_plans_id_delete(self) -> None:
        """Test case for api_v1_plans_id_delete

        Desactivar plan (soft-delete)
        """
        pass

    def test_api_v1_plans_id_put(self) -> None:
        """Test case for api_v1_plans_id_put

        Actualizar plan (precio, docs, nombre, estado)
        """
        pass

    def test_api_v1_plans_post(self) -> None:
        """Test case for api_v1_plans_post

        Crear plan
        """
        pass


if __name__ == '__main__':
    unittest.main()
