# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.get_ticket_status200_response import GetTicketStatus200Response

class TestGetTicketStatus200Response(unittest.TestCase):
    """GetTicketStatus200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetTicketStatus200Response:
        """Test GetTicketStatus200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetTicketStatus200Response`
        """
        model = GetTicketStatus200Response()
        if include_optional:
            return GetTicketStatus200Response(
                success = True,
                message = '',
                status_code = '',
                cdr_response = intifact_sdk.models.get_ticket_status_200_response_cdr_response.getTicketStatus_200_response_cdrResponse(
                    id = '', 
                    code = '', 
                    description = '', 
                    notes = [
                        ''
                        ], )
            )
        else:
            return GetTicketStatus200Response(
                success = True,
                message = '',
                status_code = '',
        )
        """

    def testGetTicketStatus200Response(self):
        """Test GetTicketStatus200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
