# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.api_v1_companies_id_branches_post_request import ApiV1CompaniesIdBranchesPostRequest

class TestApiV1CompaniesIdBranchesPostRequest(unittest.TestCase):
    """ApiV1CompaniesIdBranchesPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1CompaniesIdBranchesPostRequest:
        """Test ApiV1CompaniesIdBranchesPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1CompaniesIdBranchesPostRequest`
        """
        model = ApiV1CompaniesIdBranchesPostRequest()
        if include_optional:
            return ApiV1CompaniesIdBranchesPostRequest(
                codigo = '0480',
                nombre = '',
                ubigeo = '012345',
                direccion = '',
                departamento = '',
                provincia = '',
                distrito = '',
                urbanizacion = '',
                is_active = True
            )
        else:
            return ApiV1CompaniesIdBranchesPostRequest(
                codigo = '0480',
        )
        """

    def testApiV1CompaniesIdBranchesPostRequest(self):
        """Test ApiV1CompaniesIdBranchesPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
