# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.api_v1_summary_send_post_request_items_inner import ApiV1SummarySendPostRequestItemsInner

class TestApiV1SummarySendPostRequestItemsInner(unittest.TestCase):
    """ApiV1SummarySendPostRequestItemsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1SummarySendPostRequestItemsInner:
        """Test ApiV1SummarySendPostRequestItemsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1SummarySendPostRequestItemsInner`
        """
        model = ApiV1SummarySendPostRequestItemsInner()
        if include_optional:
            return ApiV1SummarySendPostRequestItemsInner(
                tipo_doc = '',
                serie = 'W8Q6',
                correlativo = '480728',
                cliente_tipo_doc = '',
                cliente_num_doc = '',
                estado_item = '1',
                tipo_moneda = 'PEN',
                monto_oper_gravadas = 1.337,
                monto_oper_exoneradas = 1.337,
                monto_oper_inafectas = 1.337,
                monto_oper_gratuitas = 1.337,
                monto_igv = 1.337,
                monto_isc = 1.337,
                monto_otros_cargos = 1.337,
                monto_total = 1.337
            )
        else:
            return ApiV1SummarySendPostRequestItemsInner(
                tipo_doc = '',
                serie = 'W8Q6',
                correlativo = '480728',
                cliente_tipo_doc = '',
                cliente_num_doc = '',
                estado_item = '1',
                monto_total = 1.337,
        )
        """

    def testApiV1SummarySendPostRequestItemsInner(self):
        """Test ApiV1SummarySendPostRequestItemsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
