# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.search_producto_sunat200_response import SearchProductoSunat200Response

class TestSearchProductoSunat200Response(unittest.TestCase):
    """SearchProductoSunat200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchProductoSunat200Response:
        """Test SearchProductoSunat200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchProductoSunat200Response`
        """
        model = SearchProductoSunat200Response()
        if include_optional:
            return SearchProductoSunat200Response(
                success = True,
                data = intifact_sdk.models.search_producto_sunat_200_response_data.searchProductoSunat_200_response_data(
                    version = '', 
                    q = '', 
                    total = 1.337, 
                    items = [
                        intifact_sdk.models.export_producto_sunat_200_response_data_items_inner.exportProductoSunat_200_response_data_items_inner(
                            codigo = '', 
                            descripcion = '', 
                            nivel = 'CLASE', 
                            clase_codigo = '', 
                            familia = '', 
                            segmento = '', )
                        ], )
            )
        else:
            return SearchProductoSunat200Response(
                success = True,
                data = intifact_sdk.models.search_producto_sunat_200_response_data.searchProductoSunat_200_response_data(
                    version = '', 
                    q = '', 
                    total = 1.337, 
                    items = [
                        intifact_sdk.models.export_producto_sunat_200_response_data_items_inner.exportProductoSunat_200_response_data_items_inner(
                            codigo = '', 
                            descripcion = '', 
                            nivel = 'CLASE', 
                            clase_codigo = '', 
                            familia = '', 
                            segmento = '', )
                        ], ),
        )
        """

    def testSearchProductoSunat200Response(self):
        """Test SearchProductoSunat200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
