# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.api.queues_api import QueuesApi


class TestQueuesApi(unittest.TestCase):
    """QueuesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = QueuesApi()

    def tearDown(self) -> None:
        pass

    def test_api_v1_queues_stats_get(self) -> None:
        """Test case for api_v1_queues_stats_get

        Estado de las colas BullMQ
        """
        pass


if __name__ == '__main__':
    unittest.main()
