# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.get_next_correlativo200_response_data import GetNextCorrelativo200ResponseData

class TestGetNextCorrelativo200ResponseData(unittest.TestCase):
    """GetNextCorrelativo200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetNextCorrelativo200ResponseData:
        """Test GetNextCorrelativo200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetNextCorrelativo200ResponseData`
        """
        model = GetNextCorrelativo200ResponseData()
        if include_optional:
            return GetNextCorrelativo200ResponseData(
                next = ''
            )
        else:
            return GetNextCorrelativo200ResponseData(
                next = '',
        )
        """

    def testGetNextCorrelativo200ResponseData(self):
        """Test GetNextCorrelativo200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
