# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.api_v1_voided_send_post_request import ApiV1VoidedSendPostRequest

class TestApiV1VoidedSendPostRequest(unittest.TestCase):
    """ApiV1VoidedSendPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1VoidedSendPostRequest:
        """Test ApiV1VoidedSendPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1VoidedSendPostRequest`
        """
        model = ApiV1VoidedSendPostRequest()
        if include_optional:
            return ApiV1VoidedSendPostRequest(
                empresa_ruc = '012345678910',
                correlativo = '480728',
                fecha_emision = '',
                fecha_referencia = '',
                items = [
                    intifact_sdk.models._api_v1_voided_send_post_request_items_inner._api_v1_voided_send_post_request_items_inner(
                        tipo_doc = '', 
                        serie = 'W8Q6', 
                        correlativo = '480728', 
                        motivo_baja = '0', )
                    ]
            )
        else:
            return ApiV1VoidedSendPostRequest(
                empresa_ruc = '012345678910',
                correlativo = '480728',
                fecha_emision = '',
                fecha_referencia = '',
                items = [
                    intifact_sdk.models._api_v1_voided_send_post_request_items_inner._api_v1_voided_send_post_request_items_inner(
                        tipo_doc = '', 
                        serie = 'W8Q6', 
                        correlativo = '480728', 
                        motivo_baja = '0', )
                    ],
        )
        """

    def testApiV1VoidedSendPostRequest(self):
        """Test ApiV1VoidedSendPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
