# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.api_v1_documents_next_correlativo_get200_response import ApiV1DocumentsNextCorrelativoGet200Response

class TestApiV1DocumentsNextCorrelativoGet200Response(unittest.TestCase):
    """ApiV1DocumentsNextCorrelativoGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1DocumentsNextCorrelativoGet200Response:
        """Test ApiV1DocumentsNextCorrelativoGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1DocumentsNextCorrelativoGet200Response`
        """
        model = ApiV1DocumentsNextCorrelativoGet200Response()
        if include_optional:
            return ApiV1DocumentsNextCorrelativoGet200Response(
                success = True,
                data = intifact_sdk.models._api_v1_documents_next_correlativo_get_200_response_data._api_v1_documents_next_correlativo_get_200_response_data(
                    next = '', )
            )
        else:
            return ApiV1DocumentsNextCorrelativoGet200Response(
                success = True,
                data = intifact_sdk.models._api_v1_documents_next_correlativo_get_200_response_data._api_v1_documents_next_correlativo_get_200_response_data(
                    next = '', ),
        )
        """

    def testApiV1DocumentsNextCorrelativoGet200Response(self):
        """Test ApiV1DocumentsNextCorrelativoGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
