# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.api_v1_invoice_send_post_request_pagos_inner import ApiV1InvoiceSendPostRequestPagosInner

class TestApiV1InvoiceSendPostRequestPagosInner(unittest.TestCase):
    """ApiV1InvoiceSendPostRequestPagosInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1InvoiceSendPostRequestPagosInner:
        """Test ApiV1InvoiceSendPostRequestPagosInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1InvoiceSendPostRequestPagosInner`
        """
        model = ApiV1InvoiceSendPostRequestPagosInner()
        if include_optional:
            return ApiV1InvoiceSendPostRequestPagosInner(
                metodo_pago = '',
                monto = 1.337
            )
        else:
            return ApiV1InvoiceSendPostRequestPagosInner(
                metodo_pago = '',
                monto = 1.337,
        )
        """

    def testApiV1InvoiceSendPostRequestPagosInner(self):
        """Test ApiV1InvoiceSendPostRequestPagosInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
