# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.get_queue_stats200_response_data import GetQueueStats200ResponseData

class TestGetQueueStats200ResponseData(unittest.TestCase):
    """GetQueueStats200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetQueueStats200ResponseData:
        """Test GetQueueStats200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetQueueStats200ResponseData`
        """
        model = GetQueueStats200ResponseData()
        if include_optional:
            return GetQueueStats200ResponseData(
                sunat_send = {
                    'key' : 1.337
                    },
                sunat_summary = {
                    'key' : 1.337
                    },
                sunat_ticket_poll = {
                    'key' : 1.337
                    },
                sunat_gre_send = {
                    'key' : 1.337
                    },
                sunat_gre_ticket_poll = {
                    'key' : 1.337
                    }
            )
        else:
            return GetQueueStats200ResponseData(
                sunat_send = {
                    'key' : 1.337
                    },
                sunat_summary = {
                    'key' : 1.337
                    },
                sunat_ticket_poll = {
                    'key' : 1.337
                    },
                sunat_gre_send = {
                    'key' : 1.337
                    },
                sunat_gre_ticket_poll = {
                    'key' : 1.337
                    },
        )
        """

    def testGetQueueStats200ResponseData(self):
        """Test GetQueueStats200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
