# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.api_v1_invoice_compute_post200_response_data import ApiV1InvoiceComputePost200ResponseData

class TestApiV1InvoiceComputePost200ResponseData(unittest.TestCase):
    """ApiV1InvoiceComputePost200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1InvoiceComputePost200ResponseData:
        """Test ApiV1InvoiceComputePost200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1InvoiceComputePost200ResponseData`
        """
        model = ApiV1InvoiceComputePost200ResponseData()
        if include_optional:
            return ApiV1InvoiceComputePost200ResponseData(
                tipo_moneda = '',
                items = [
                    intifact_sdk.models._api_v1_invoice_compute_post_200_response_data_items_inner._api_v1_invoice_compute_post_200_response_data_items_inner(
                        unidad = '', 
                        cantidad = 1.337, 
                        cod_producto = '', 
                        descripcion = '', 
                        marca = '', 
                        tip_afe_igv = '', 
                        porcentaje_igv = 1.337, 
                        monto_valor_unitario = 1.337, 
                        descuento = 1.337, 
                        descuento_item = 1.337, 
                        descuento_global_linea = 1.337, 
                        monto_bruto = 1.337, 
                        monto_valor_venta = 1.337, 
                        monto_base_igv = 1.337, 
                        igv = 1.337, 
                        total_impuestos = 1.337, 
                        monto_precio_unitario = 1.337, 
                        factor_icbper = 1.337, 
                        cod_prod_sunat = '', )
                    ],
                monto_oper_gravadas = 1.337,
                monto_oper_exoneradas = 1.337,
                monto_oper_inafectas = 1.337,
                monto_oper_gratuitas = 1.337,
                monto_oper_exportacion = 1.337,
                monto_igv = 1.337,
                monto_icbper = 1.337,
                descuento_global = 1.337,
                descuento_global_base = 1.337,
                total_descuentos = 1.337,
                total_impuestos = 1.337,
                valor_venta = 1.337,
                sub_total = 1.337,
                monto_imp_venta = 1.337,
                monto_en_letras = ''
            )
        else:
            return ApiV1InvoiceComputePost200ResponseData(
                tipo_moneda = '',
                items = [
                    intifact_sdk.models._api_v1_invoice_compute_post_200_response_data_items_inner._api_v1_invoice_compute_post_200_response_data_items_inner(
                        unidad = '', 
                        cantidad = 1.337, 
                        cod_producto = '', 
                        descripcion = '', 
                        marca = '', 
                        tip_afe_igv = '', 
                        porcentaje_igv = 1.337, 
                        monto_valor_unitario = 1.337, 
                        descuento = 1.337, 
                        descuento_item = 1.337, 
                        descuento_global_linea = 1.337, 
                        monto_bruto = 1.337, 
                        monto_valor_venta = 1.337, 
                        monto_base_igv = 1.337, 
                        igv = 1.337, 
                        total_impuestos = 1.337, 
                        monto_precio_unitario = 1.337, 
                        factor_icbper = 1.337, 
                        cod_prod_sunat = '', )
                    ],
                monto_oper_gravadas = 1.337,
                monto_oper_exoneradas = 1.337,
                monto_oper_inafectas = 1.337,
                monto_oper_gratuitas = 1.337,
                monto_oper_exportacion = 1.337,
                monto_igv = 1.337,
                monto_icbper = 1.337,
                descuento_global = 1.337,
                descuento_global_base = 1.337,
                total_descuentos = 1.337,
                total_impuestos = 1.337,
                valor_venta = 1.337,
                sub_total = 1.337,
                monto_imp_venta = 1.337,
                monto_en_letras = '',
        )
        """

    def testApiV1InvoiceComputePost200ResponseData(self):
        """Test ApiV1InvoiceComputePost200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
