# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.api_v1_despatch_send_multi_post202_response_data_guias_inner import ApiV1DespatchSendMultiPost202ResponseDataGuiasInner

class TestApiV1DespatchSendMultiPost202ResponseDataGuiasInner(unittest.TestCase):
    """ApiV1DespatchSendMultiPost202ResponseDataGuiasInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1DespatchSendMultiPost202ResponseDataGuiasInner:
        """Test ApiV1DespatchSendMultiPost202ResponseDataGuiasInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1DespatchSendMultiPost202ResponseDataGuiasInner`
        """
        model = ApiV1DespatchSendMultiPost202ResponseDataGuiasInner()
        if include_optional:
            return ApiV1DespatchSendMultiPost202ResponseDataGuiasInner(
                success = True,
                message = '',
                code = '',
                destino = 1.337,
                data = intifact_sdk.models._api_v1_note_send_post_202_response_data._api_v1_note_send_post_202_response_data(
                    id = 'ffffffff-ffff-ffff-ffff-ffffffffffff', 
                    estado = '', 
                    hash = '', 
                    signature_value = '', 
                    job_id = '', )
            )
        else:
            return ApiV1DespatchSendMultiPost202ResponseDataGuiasInner(
                success = True,
                message = '',
                destino = 1.337,
        )
        """

    def testApiV1DespatchSendMultiPost202ResponseDataGuiasInner(self):
        """Test ApiV1DespatchSendMultiPost202ResponseDataGuiasInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
