# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.send_invoice_request_forma_pago_inner import SendInvoiceRequestFormaPagoInner

class TestSendInvoiceRequestFormaPagoInner(unittest.TestCase):
    """SendInvoiceRequestFormaPagoInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendInvoiceRequestFormaPagoInner:
        """Test SendInvoiceRequestFormaPagoInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendInvoiceRequestFormaPagoInner`
        """
        model = SendInvoiceRequestFormaPagoInner()
        if include_optional:
            return SendInvoiceRequestFormaPagoInner(
                tipo = 'Contado',
                monto = 0,
                cuota = 0,
                fecha_pago = ''
            )
        else:
            return SendInvoiceRequestFormaPagoInner(
                tipo = 'Contado',
                monto = 0,
                fecha_pago = '',
        )
        """

    def testSendInvoiceRequestFormaPagoInner(self):
        """Test SendInvoiceRequestFormaPagoInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
