# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.send_despatch_multi_request import SendDespatchMultiRequest

class TestSendDespatchMultiRequest(unittest.TestCase):
    """SendDespatchMultiRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SendDespatchMultiRequest:
        """Test SendDespatchMultiRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SendDespatchMultiRequest`
        """
        model = SendDespatchMultiRequest()
        if include_optional:
            return SendDespatchMultiRequest(
                tipo_doc = '09',
                serie = 'W8Q6',
                observacion = '',
                fecha_emision = '',
                empresa_ruc = '012345678910',
                establecimiento_codigo = '0000',
                guia_cod_traslado = '0',
                guia_mod_traslado = '01',
                guia_fec_traslado = '',
                guia_vehiculo_placa = '',
                transportista_tipo_doc = '',
                transportista_num_doc = '',
                transportista_razon_social = '',
                transportista_nro_mtc = '8',
                guia_partida_ubigeo = '012345',
                guia_partida_direccion = '0',
                chofer = [
                    intifact_sdk.models.send_despatch_request_chofer_inner.sendDespatch_request_chofer_inner(
                        tipo = 'Principal', 
                        tipo_doc = '0', 
                        nro_doc = '0', 
                        licencia = '0', 
                        nombres = '0', 
                        apellidos = '0', )
                    ],
                guia_fec_entrega = '',
                guia_des_traslado = '',
                guia_peso_neto = 0,
                guia_sustento_peso = '',
                guia_num_bultos = 0,
                indicadores = intifact_sdk.models.send_despatch_request_indicadores.sendDespatch_request_indicadores(
                    transbordo_programado = True, 
                    vehiculo_m1_l = True, 
                    retorno_vehiculo_envase_vacio = True, 
                    retorno_vehiculo_vacio = True, 
                    traslado_total_dam_ds = True, 
                    registro_transportista = True, 
                    traslado_contenedor_manifiesto = True, ),
                contenedores = [
                    intifact_sdk.models.send_despatch_request_contenedores_inner.sendDespatch_request_contenedores_inner(
                        numero = '0', 
                        precinto = '', )
                    ],
                guia_vehiculo_tuc = '',
                guia_vehiculo_autorizacion = '',
                guia_vehiculo_autorizacion_entidad = '',
                vehiculos_secundarios = [
                    intifact_sdk.models.send_despatch_request_vehiculos_secundarios_inner.sendDespatch_request_vehiculosSecundarios_inner(
                        placa = '0', 
                        tuc = '', 
                        autorizacion = '', 
                        autorizacion_entidad = '', )
                    ],
                transportista_autorizacion = '',
                transportista_autorizacion_entidad = '',
                guia_partida_ruc = '012345678910',
                guia_partida_cod_local = '',
                guia_partida_geo = intifact_sdk.models.send_despatch_request_guia_llegada_geo.sendDespatch_request_guiaLlegadaGeo(
                    lat = '', 
                    lon = '', ),
                guia_llegada_ruc = '012345678910',
                guia_llegada_cod_local = '',
                guia_llegada_geo = intifact_sdk.models.send_despatch_request_guia_llegada_geo.sendDespatch_request_guiaLlegadaGeo(
                    lat = '', 
                    lon = '', ),
                documentos_relacionados = [
                    intifact_sdk.models.send_despatch_request_documentos_relacionados_inner.sendDespatch_request_documentosRelacionados_inner(
                        cod_tipo = '0', 
                        numero = '0', 
                        tipo_desc = '', 
                        emisor_ruc = '012345678910', )
                    ],
                remitente_autorizacion = '',
                remitente_autorizacion_entidad = '',
                proveedor_tipo_doc = '',
                proveedor_num_doc = '',
                proveedor_razon_social = '',
                comprador_tipo_doc = '',
                comprador_num_doc = '',
                comprador_razon_social = '',
                puerto_codigo = '',
                puerto_nombre = '',
                puerto_tipo = '',
                destinos = [
                    intifact_sdk.models.send_despatch_multi_request_destinos_inner.sendDespatchMulti_request_destinos_inner(
                        cliente_tipo_doc = '0', 
                        cliente_num_doc = '0', 
                        cliente_razon_social = '0', 
                        cliente_direccion = '', 
                        cliente_distrito = '', 
                        cliente_provincia = '', 
                        cliente_departamento = '', 
                        destinatario_contacto = '', 
                        destinatario_telefono = '', 
                        destinatario_email = '', 
                        entrega_referencia = '', 
                        modalidad_entrega = 'DOMICILIO', 
                        agencia_nombre = '', 
                        agencia_sede = '', 
                        guia_llegada_ubigeo = '012345', 
                        guia_llegada_direccion = '0', 
                        guia_peso_total = 0, 
                        guia_und_peso_total = 'KGM', 
                        detalle = [
                            intifact_sdk.models.send_despatch_request_detalle_inner.sendDespatch_request_detalle_inner(
                                unidad = '0', 
                                cantidad = 0, 
                                cod_producto = '0', 
                                descripcion = '0', )
                            ], )
                    ]
            )
        else:
            return SendDespatchMultiRequest(
                tipo_doc = '09',
                serie = 'W8Q6',
                fecha_emision = '',
                empresa_ruc = '012345678910',
                guia_cod_traslado = '0',
                guia_mod_traslado = '01',
                guia_fec_traslado = '',
                guia_partida_ubigeo = '012345',
                guia_partida_direccion = '0',
                destinos = [
                    intifact_sdk.models.send_despatch_multi_request_destinos_inner.sendDespatchMulti_request_destinos_inner(
                        cliente_tipo_doc = '0', 
                        cliente_num_doc = '0', 
                        cliente_razon_social = '0', 
                        cliente_direccion = '', 
                        cliente_distrito = '', 
                        cliente_provincia = '', 
                        cliente_departamento = '', 
                        destinatario_contacto = '', 
                        destinatario_telefono = '', 
                        destinatario_email = '', 
                        entrega_referencia = '', 
                        modalidad_entrega = 'DOMICILIO', 
                        agencia_nombre = '', 
                        agencia_sede = '', 
                        guia_llegada_ubigeo = '012345', 
                        guia_llegada_direccion = '0', 
                        guia_peso_total = 0, 
                        guia_und_peso_total = 'KGM', 
                        detalle = [
                            intifact_sdk.models.send_despatch_request_detalle_inner.sendDespatch_request_detalle_inner(
                                unidad = '0', 
                                cantidad = 0, 
                                cod_producto = '0', 
                                descripcion = '0', )
                            ], )
                    ],
        )
        """

    def testSendDespatchMultiRequest(self):
        """Test SendDespatchMultiRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
