# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.api_v1_queues_stats_get200_response import ApiV1QueuesStatsGet200Response

class TestApiV1QueuesStatsGet200Response(unittest.TestCase):
    """ApiV1QueuesStatsGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1QueuesStatsGet200Response:
        """Test ApiV1QueuesStatsGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1QueuesStatsGet200Response`
        """
        model = ApiV1QueuesStatsGet200Response()
        if include_optional:
            return ApiV1QueuesStatsGet200Response(
                success = True,
                data = intifact_sdk.models._api_v1_queues_stats_get_200_response_data._api_v1_queues_stats_get_200_response_data(
                    sunat_send = {
                        'key' : 1.337
                        }, 
                    sunat_summary = {
                        'key' : 1.337
                        }, 
                    sunat_ticket_poll = {
                        'key' : 1.337
                        }, 
                    sunat_gre_send = , 
                    sunat_gre_ticket_poll = , )
            )
        else:
            return ApiV1QueuesStatsGet200Response(
                success = True,
                data = intifact_sdk.models._api_v1_queues_stats_get_200_response_data._api_v1_queues_stats_get_200_response_data(
                    sunat_send = {
                        'key' : 1.337
                        }, 
                    sunat_summary = {
                        'key' : 1.337
                        }, 
                    sunat_ticket_poll = {
                        'key' : 1.337
                        }, 
                    sunat_gre_send = , 
                    sunat_gre_ticket_poll = , ),
        )
        """

    def testApiV1QueuesStatsGet200Response(self):
        """Test ApiV1QueuesStatsGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
