# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.api_v1_despatch_send_post_request_documentos_relacionados_inner import ApiV1DespatchSendPostRequestDocumentosRelacionadosInner

class TestApiV1DespatchSendPostRequestDocumentosRelacionadosInner(unittest.TestCase):
    """ApiV1DespatchSendPostRequestDocumentosRelacionadosInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1DespatchSendPostRequestDocumentosRelacionadosInner:
        """Test ApiV1DespatchSendPostRequestDocumentosRelacionadosInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1DespatchSendPostRequestDocumentosRelacionadosInner`
        """
        model = ApiV1DespatchSendPostRequestDocumentosRelacionadosInner()
        if include_optional:
            return ApiV1DespatchSendPostRequestDocumentosRelacionadosInner(
                cod_tipo = '0',
                numero = '0',
                tipo_desc = '',
                emisor_ruc = '012345678910'
            )
        else:
            return ApiV1DespatchSendPostRequestDocumentosRelacionadosInner(
                cod_tipo = '0',
                numero = '0',
        )
        """

    def testApiV1DespatchSendPostRequestDocumentosRelacionadosInner(self):
        """Test ApiV1DespatchSendPostRequestDocumentosRelacionadosInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
