# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.api_v1_webhooks_id_put_request import ApiV1WebhooksIdPutRequest

class TestApiV1WebhooksIdPutRequest(unittest.TestCase):
    """ApiV1WebhooksIdPutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1WebhooksIdPutRequest:
        """Test ApiV1WebhooksIdPutRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1WebhooksIdPutRequest`
        """
        model = ApiV1WebhooksIdPutRequest()
        if include_optional:
            return ApiV1WebhooksIdPutRequest(
                url = '',
                events = [
                    'document.accepted'
                    ],
                description = '',
                is_active = True
            )
        else:
            return ApiV1WebhooksIdPutRequest(
        )
        """

    def testApiV1WebhooksIdPutRequest(self):
        """Test ApiV1WebhooksIdPutRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
