# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.api_v1_despatch_send_multi_post202_response import ApiV1DespatchSendMultiPost202Response

class TestApiV1DespatchSendMultiPost202Response(unittest.TestCase):
    """ApiV1DespatchSendMultiPost202Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1DespatchSendMultiPost202Response:
        """Test ApiV1DespatchSendMultiPost202Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1DespatchSendMultiPost202Response`
        """
        model = ApiV1DespatchSendMultiPost202Response()
        if include_optional:
            return ApiV1DespatchSendMultiPost202Response(
                success = True,
                message = '',
                data = intifact_sdk.models._api_v1_despatch_send_multi_post_202_response_data._api_v1_despatch_send_multi_post_202_response_data(
                    total = 1.337, 
                    emitidas = 1.337, 
                    fallidas = 1.337, 
                    guias = [
                        intifact_sdk.models._api_v1_despatch_send_multi_post_202_response_data_guias_inner._api_v1_despatch_send_multi_post_202_response_data_guias_inner(
                            success = True, 
                            message = '', 
                            code = '', 
                            destino = 1.337, 
                            data = intifact_sdk.models._api_v1_note_send_post_202_response_data._api_v1_note_send_post_202_response_data(
                                id = 'ffffffff-ffff-ffff-ffff-ffffffffffff', 
                                estado = '', 
                                hash = '', 
                                signature_value = '', 
                                job_id = '', ), )
                        ], )
            )
        else:
            return ApiV1DespatchSendMultiPost202Response(
                success = True,
                message = '',
        )
        """

    def testApiV1DespatchSendMultiPost202Response(self):
        """Test ApiV1DespatchSendMultiPost202Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
