# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.api_v1_invoice_send_post202_response_data import ApiV1InvoiceSendPost202ResponseData

class TestApiV1InvoiceSendPost202ResponseData(unittest.TestCase):
    """ApiV1InvoiceSendPost202ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1InvoiceSendPost202ResponseData:
        """Test ApiV1InvoiceSendPost202ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1InvoiceSendPost202ResponseData`
        """
        model = ApiV1InvoiceSendPost202ResponseData()
        if include_optional:
            return ApiV1InvoiceSendPost202ResponseData(
                id = 'ffffffff-ffff-ffff-ffff-ffffffffffff',
                estado = '',
                hash = '',
                signature_value = '',
                job_id = ''
            )
        else:
            return ApiV1InvoiceSendPost202ResponseData(
                id = 'ffffffff-ffff-ffff-ffff-ffffffffffff',
                estado = '',
                hash = '',
                signature_value = '',
        )
        """

    def testApiV1InvoiceSendPost202ResponseData(self):
        """Test ApiV1InvoiceSendPost202ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
