# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from intifact_sdk.models.api_v1_catalogs_get200_response_data_inner_items_inner import ApiV1CatalogsGet200ResponseDataInnerItemsInner

class TestApiV1CatalogsGet200ResponseDataInnerItemsInner(unittest.TestCase):
    """ApiV1CatalogsGet200ResponseDataInnerItemsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiV1CatalogsGet200ResponseDataInnerItemsInner:
        """Test ApiV1CatalogsGet200ResponseDataInnerItemsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiV1CatalogsGet200ResponseDataInnerItemsInner`
        """
        model = ApiV1CatalogsGet200ResponseDataInnerItemsInner()
        if include_optional:
            return ApiV1CatalogsGet200ResponseDataInnerItemsInner(
                code = '',
                label = ''
            )
        else:
            return ApiV1CatalogsGet200ResponseDataInnerItemsInner(
                code = '',
                label = '',
        )
        """

    def testApiV1CatalogsGet200ResponseDataInnerItemsInner(self):
        """Test ApiV1CatalogsGet200ResponseDataInnerItemsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
