# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from intifact_sdk.models.api_v1_documents_get200_response_data_inner_company import ApiV1DocumentsGet200ResponseDataInnerCompany
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ApiV1DocumentsGet200ResponseDataInner(BaseModel):
    """
    ApiV1DocumentsGet200ResponseDataInner
    """ # noqa: E501
    id: Optional[StrictStr]
    env: StrictStr
    tipo_doc: Optional[StrictStr] = Field(alias="tipoDoc")
    serie: Optional[StrictStr]
    correlativo: Optional[StrictStr]
    fecha_emision: Optional[StrictStr] = Field(alias="fechaEmision")
    tipo_moneda: Optional[StrictStr] = Field(alias="tipoMoneda")
    cliente_num_doc: Optional[StrictStr] = Field(alias="clienteNumDoc")
    cliente_razon_social: Optional[StrictStr] = Field(alias="clienteRazonSocial")
    monto_imp_venta: Optional[StrictStr] = Field(alias="montoImpVenta")
    monto_igv: Optional[StrictStr] = Field(default=None, alias="montoIgv")
    estado_sunat: Optional[StrictStr] = Field(alias="estadoSunat")
    codigo_respuesta: Optional[StrictStr] = Field(alias="codigoRespuesta")
    descripcion_respuesta: Optional[StrictStr] = Field(default=None, alias="descripcionRespuesta")
    hash_cdr: Optional[StrictStr] = Field(alias="hashCdr")
    created_at: Optional[StrictStr] = Field(alias="createdAt")
    company: ApiV1DocumentsGet200ResponseDataInnerCompany
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "env", "tipoDoc", "serie", "correlativo", "fechaEmision", "tipoMoneda", "clienteNumDoc", "clienteRazonSocial", "montoImpVenta", "montoIgv", "estadoSunat", "codigoRespuesta", "descripcionRespuesta", "hashCdr", "createdAt", "company"]

    @field_validator('env')
    def env_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['live', 'test']):
            raise ValueError("must be one of enum values ('live', 'test')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApiV1DocumentsGet200ResponseDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of company
        if self.company:
            _dict['company'] = self.company.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if tipo_doc (nullable) is None
        # and model_fields_set contains the field
        if self.tipo_doc is None and "tipo_doc" in self.model_fields_set:
            _dict['tipoDoc'] = None

        # set to None if serie (nullable) is None
        # and model_fields_set contains the field
        if self.serie is None and "serie" in self.model_fields_set:
            _dict['serie'] = None

        # set to None if correlativo (nullable) is None
        # and model_fields_set contains the field
        if self.correlativo is None and "correlativo" in self.model_fields_set:
            _dict['correlativo'] = None

        # set to None if fecha_emision (nullable) is None
        # and model_fields_set contains the field
        if self.fecha_emision is None and "fecha_emision" in self.model_fields_set:
            _dict['fechaEmision'] = None

        # set to None if tipo_moneda (nullable) is None
        # and model_fields_set contains the field
        if self.tipo_moneda is None and "tipo_moneda" in self.model_fields_set:
            _dict['tipoMoneda'] = None

        # set to None if cliente_num_doc (nullable) is None
        # and model_fields_set contains the field
        if self.cliente_num_doc is None and "cliente_num_doc" in self.model_fields_set:
            _dict['clienteNumDoc'] = None

        # set to None if cliente_razon_social (nullable) is None
        # and model_fields_set contains the field
        if self.cliente_razon_social is None and "cliente_razon_social" in self.model_fields_set:
            _dict['clienteRazonSocial'] = None

        # set to None if monto_imp_venta (nullable) is None
        # and model_fields_set contains the field
        if self.monto_imp_venta is None and "monto_imp_venta" in self.model_fields_set:
            _dict['montoImpVenta'] = None

        # set to None if monto_igv (nullable) is None
        # and model_fields_set contains the field
        if self.monto_igv is None and "monto_igv" in self.model_fields_set:
            _dict['montoIgv'] = None

        # set to None if estado_sunat (nullable) is None
        # and model_fields_set contains the field
        if self.estado_sunat is None and "estado_sunat" in self.model_fields_set:
            _dict['estadoSunat'] = None

        # set to None if codigo_respuesta (nullable) is None
        # and model_fields_set contains the field
        if self.codigo_respuesta is None and "codigo_respuesta" in self.model_fields_set:
            _dict['codigoRespuesta'] = None

        # set to None if descripcion_respuesta (nullable) is None
        # and model_fields_set contains the field
        if self.descripcion_respuesta is None and "descripcion_respuesta" in self.model_fields_set:
            _dict['descripcionRespuesta'] = None

        # set to None if hash_cdr (nullable) is None
        # and model_fields_set contains the field
        if self.hash_cdr is None and "hash_cdr" in self.model_fields_set:
            _dict['hashCdr'] = None

        # set to None if created_at (nullable) is None
        # and model_fields_set contains the field
        if self.created_at is None and "created_at" in self.model_fields_set:
            _dict['createdAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApiV1DocumentsGet200ResponseDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "env": obj.get("env"),
            "tipoDoc": obj.get("tipoDoc"),
            "serie": obj.get("serie"),
            "correlativo": obj.get("correlativo"),
            "fechaEmision": obj.get("fechaEmision"),
            "tipoMoneda": obj.get("tipoMoneda"),
            "clienteNumDoc": obj.get("clienteNumDoc"),
            "clienteRazonSocial": obj.get("clienteRazonSocial"),
            "montoImpVenta": obj.get("montoImpVenta"),
            "montoIgv": obj.get("montoIgv"),
            "estadoSunat": obj.get("estadoSunat"),
            "codigoRespuesta": obj.get("codigoRespuesta"),
            "descripcionRespuesta": obj.get("descripcionRespuesta"),
            "hashCdr": obj.get("hashCdr"),
            "createdAt": obj.get("createdAt"),
            "company": ApiV1DocumentsGet200ResponseDataInnerCompany.from_dict(obj["company"]) if obj.get("company") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


