# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreatePlanRequest(BaseModel):
    """
    CreatePlanRequest
    """ # noqa: E501
    code: Annotated[str, Field(min_length=1, strict=True, max_length=30)]
    name: Annotated[str, Field(min_length=1, strict=True, max_length=100)]
    monthly_docs: Optional[Annotated[int, Field(le=9007199254740991, strict=True, ge=0)]] = Field(default=0, alias="monthlyDocs")
    max_rucs: Optional[Annotated[int, Field(le=9007199254740991, strict=True, ge=0)]] = Field(default=0, alias="maxRucs")
    requests_per_minute: Optional[Annotated[int, Field(le=9007199254740991, strict=True, ge=0)]] = Field(default=0, alias="requestsPerMinute")
    allow_despatch: Optional[StrictBool] = Field(default=True, alias="allowDespatch")
    price: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = 0
    currency: Optional[Annotated[str, Field(min_length=3, strict=True, max_length=3)]] = 'PEN'
    sort_order: Optional[Annotated[int, Field(le=9007199254740991, strict=True, ge=-9007199254740991)]] = Field(default=0, alias="sortOrder")
    is_active: Optional[StrictBool] = Field(default=True, alias="isActive")
    __properties: ClassVar[List[str]] = ["code", "name", "monthlyDocs", "maxRucs", "requestsPerMinute", "allowDespatch", "price", "currency", "sortOrder", "isActive"]

    @field_validator('code', mode="before")
    def code_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^[a-z0-9_-]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-z0-9_-]+$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreatePlanRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreatePlanRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "code": obj.get("code"),
            "name": obj.get("name"),
            "monthlyDocs": obj.get("monthlyDocs") if obj.get("monthlyDocs") is not None else 0,
            "maxRucs": obj.get("maxRucs") if obj.get("maxRucs") is not None else 0,
            "requestsPerMinute": obj.get("requestsPerMinute") if obj.get("requestsPerMinute") is not None else 0,
            "allowDespatch": obj.get("allowDespatch") if obj.get("allowDespatch") is not None else True,
            "price": obj.get("price") if obj.get("price") is not None else 0,
            "currency": obj.get("currency") if obj.get("currency") is not None else 'PEN',
            "sortOrder": obj.get("sortOrder") if obj.get("sortOrder") is not None else 0,
            "isActive": obj.get("isActive") if obj.get("isActive") is not None else True
        })
        return _obj


