# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SendSummaryRequestItemsInner(BaseModel):
    """
    SendSummaryRequestItemsInner
    """ # noqa: E501
    tipo_doc: Optional[StrictStr] = Field(alias="tipoDoc")
    serie: Annotated[str, Field(strict=True)]
    correlativo: Annotated[str, Field(strict=True)]
    cliente_tipo_doc: Optional[StrictStr] = Field(alias="clienteTipoDoc")
    cliente_num_doc: Optional[StrictStr] = Field(alias="clienteNumDoc")
    estado_item: StrictStr = Field(alias="estadoItem")
    tipo_moneda: Optional[StrictStr] = Field(default='PEN', alias="tipoMoneda")
    monto_oper_gravadas: Optional[Union[StrictFloat, StrictInt]] = Field(default=0, alias="montoOperGravadas")
    monto_oper_exoneradas: Optional[Union[StrictFloat, StrictInt]] = Field(default=0, alias="montoOperExoneradas")
    monto_oper_inafectas: Optional[Union[StrictFloat, StrictInt]] = Field(default=0, alias="montoOperInafectas")
    monto_oper_gratuitas: Optional[Union[StrictFloat, StrictInt]] = Field(default=0, alias="montoOperGratuitas")
    monto_igv: Optional[Union[StrictFloat, StrictInt]] = Field(default=0, alias="montoIgv")
    monto_isc: Optional[Union[StrictFloat, StrictInt]] = Field(default=0, alias="montoIsc")
    monto_otros_cargos: Optional[Union[StrictFloat, StrictInt]] = Field(default=0, alias="montoOtrosCargos")
    monto_total: Union[StrictFloat, StrictInt] = Field(alias="montoTotal")
    __properties: ClassVar[List[str]] = ["tipoDoc", "serie", "correlativo", "clienteTipoDoc", "clienteNumDoc", "estadoItem", "tipoMoneda", "montoOperGravadas", "montoOperExoneradas", "montoOperInafectas", "montoOperGratuitas", "montoIgv", "montoIsc", "montoOtrosCargos", "montoTotal"]

    @field_validator('serie', mode="before")
    def serie_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^[A-Z0-9]{4}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Z0-9]{4}$/")
        return value

    @field_validator('correlativo', mode="before")
    def correlativo_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^\d{1,8}$", value):
            raise ValueError(r"must validate the regular expression /^\d{1,8}$/")
        return value

    @field_validator('estado_item')
    def estado_item_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['1', '2', '3']):
            raise ValueError("must be one of enum values ('1', '2', '3')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SendSummaryRequestItemsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if tipo_doc (nullable) is None
        # and model_fields_set contains the field
        if self.tipo_doc is None and "tipo_doc" in self.model_fields_set:
            _dict['tipoDoc'] = None

        # set to None if cliente_tipo_doc (nullable) is None
        # and model_fields_set contains the field
        if self.cliente_tipo_doc is None and "cliente_tipo_doc" in self.model_fields_set:
            _dict['clienteTipoDoc'] = None

        # set to None if cliente_num_doc (nullable) is None
        # and model_fields_set contains the field
        if self.cliente_num_doc is None and "cliente_num_doc" in self.model_fields_set:
            _dict['clienteNumDoc'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SendSummaryRequestItemsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tipoDoc": obj.get("tipoDoc"),
            "serie": obj.get("serie"),
            "correlativo": obj.get("correlativo"),
            "clienteTipoDoc": obj.get("clienteTipoDoc"),
            "clienteNumDoc": obj.get("clienteNumDoc"),
            "estadoItem": obj.get("estadoItem"),
            "tipoMoneda": obj.get("tipoMoneda") if obj.get("tipoMoneda") is not None else 'PEN',
            "montoOperGravadas": obj.get("montoOperGravadas") if obj.get("montoOperGravadas") is not None else 0,
            "montoOperExoneradas": obj.get("montoOperExoneradas") if obj.get("montoOperExoneradas") is not None else 0,
            "montoOperInafectas": obj.get("montoOperInafectas") if obj.get("montoOperInafectas") is not None else 0,
            "montoOperGratuitas": obj.get("montoOperGratuitas") if obj.get("montoOperGratuitas") is not None else 0,
            "montoIgv": obj.get("montoIgv") if obj.get("montoIgv") is not None else 0,
            "montoIsc": obj.get("montoIsc") if obj.get("montoIsc") is not None else 0,
            "montoOtrosCargos": obj.get("montoOtrosCargos") if obj.get("montoOtrosCargos") is not None else 0,
            "montoTotal": obj.get("montoTotal")
        })
        return _obj


