# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SendVoidedRequestItemsInner(BaseModel):
    """
    SendVoidedRequestItemsInner
    """ # noqa: E501
    tipo_doc: Optional[StrictStr] = Field(alias="tipoDoc")
    serie: Annotated[str, Field(strict=True)]
    correlativo: Annotated[str, Field(strict=True)]
    motivo_baja: Annotated[str, Field(min_length=1, strict=True)] = Field(alias="motivoBaja")
    __properties: ClassVar[List[str]] = ["tipoDoc", "serie", "correlativo", "motivoBaja"]

    @field_validator('serie', mode="before")
    def serie_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^[A-Z0-9]{4}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Z0-9]{4}$/")
        return value

    @field_validator('correlativo', mode="before")
    def correlativo_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^\d{1,8}$", value):
            raise ValueError(r"must validate the regular expression /^\d{1,8}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SendVoidedRequestItemsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if tipo_doc (nullable) is None
        # and model_fields_set contains the field
        if self.tipo_doc is None and "tipo_doc" in self.model_fields_set:
            _dict['tipoDoc'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SendVoidedRequestItemsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tipoDoc": obj.get("tipoDoc"),
            "serie": obj.get("serie"),
            "correlativo": obj.get("correlativo"),
            "motivoBaja": obj.get("motivoBaja")
        })
        return _obj


