# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from intifact_sdk.models.send_despatch_multi_request_destinos_inner import SendDespatchMultiRequestDestinosInner
from intifact_sdk.models.send_despatch_request_chofer_inner import SendDespatchRequestChoferInner
from intifact_sdk.models.send_despatch_request_contenedores_inner import SendDespatchRequestContenedoresInner
from intifact_sdk.models.send_despatch_request_documentos_relacionados_inner import SendDespatchRequestDocumentosRelacionadosInner
from intifact_sdk.models.send_despatch_request_guia_llegada_geo import SendDespatchRequestGuiaLlegadaGeo
from intifact_sdk.models.send_despatch_request_indicadores import SendDespatchRequestIndicadores
from intifact_sdk.models.send_despatch_request_vehiculos_secundarios_inner import SendDespatchRequestVehiculosSecundariosInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SendDespatchMultiRequest(BaseModel):
    """
    SendDespatchMultiRequest
    """ # noqa: E501
    tipo_doc: StrictStr = Field(alias="tipoDoc")
    serie: Annotated[str, Field(strict=True)]
    observacion: Optional[Annotated[str, Field(strict=True, max_length=500)]] = None
    fecha_emision: Optional[StrictStr] = Field(alias="fechaEmision")
    empresa_ruc: Annotated[str, Field(min_length=11, strict=True, max_length=11)] = Field(alias="empresaRuc")
    establecimiento_codigo: Optional[Annotated[str, Field(strict=True)]] = Field(default='0000', alias="establecimientoCodigo")
    guia_cod_traslado: Annotated[str, Field(min_length=1, strict=True, max_length=2)] = Field(alias="guiaCodTraslado")
    guia_mod_traslado: StrictStr = Field(alias="guiaModTraslado")
    guia_fec_traslado: Optional[StrictStr] = Field(alias="guiaFecTraslado")
    guia_vehiculo_placa: Optional[Annotated[str, Field(strict=True, max_length=10)]] = Field(default=None, alias="guiaVehiculoPlaca")
    transportista_tipo_doc: Optional[StrictStr] = Field(default=None, alias="transportistaTipoDoc")
    transportista_num_doc: Optional[StrictStr] = Field(default=None, alias="transportistaNumDoc")
    transportista_razon_social: Optional[StrictStr] = Field(default=None, alias="transportistaRazonSocial")
    transportista_nro_mtc: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, alias="transportistaNroMtc")
    guia_partida_ubigeo: Annotated[str, Field(min_length=6, strict=True, max_length=6)] = Field(alias="guiaPartidaUbigeo")
    guia_partida_direccion: Annotated[str, Field(min_length=1, strict=True, max_length=500)] = Field(alias="guiaPartidaDireccion")
    chofer: Optional[Annotated[List[SendDespatchRequestChoferInner], Field(max_length=10)]] = None
    guia_fec_entrega: Optional[StrictStr] = Field(default=None, alias="guiaFecEntrega")
    guia_des_traslado: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(default=None, alias="guiaDesTraslado")
    guia_peso_neto: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, alias="guiaPesoNeto")
    guia_sustento_peso: Optional[Annotated[str, Field(strict=True, max_length=250)]] = Field(default=None, alias="guiaSustentoPeso")
    guia_num_bultos: Optional[Annotated[int, Field(le=9007199254740991, strict=True, ge=0)]] = Field(default=None, alias="guiaNumBultos")
    indicadores: Optional[SendDespatchRequestIndicadores] = None
    contenedores: Optional[Annotated[List[SendDespatchRequestContenedoresInner], Field(max_length=2)]] = None
    guia_vehiculo_tuc: Optional[Annotated[str, Field(strict=True, max_length=15)]] = Field(default=None, alias="guiaVehiculoTuc")
    guia_vehiculo_autorizacion: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, alias="guiaVehiculoAutorizacion")
    guia_vehiculo_autorizacion_entidad: Optional[Annotated[str, Field(strict=True, max_length=2)]] = Field(default=None, alias="guiaVehiculoAutorizacionEntidad")
    vehiculos_secundarios: Optional[Annotated[List[SendDespatchRequestVehiculosSecundariosInner], Field(max_length=2)]] = Field(default=None, alias="vehiculosSecundarios")
    transportista_autorizacion: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, alias="transportistaAutorizacion")
    transportista_autorizacion_entidad: Optional[Annotated[str, Field(strict=True, max_length=2)]] = Field(default=None, alias="transportistaAutorizacionEntidad")
    guia_partida_ruc: Optional[Annotated[str, Field(min_length=11, strict=True, max_length=11)]] = Field(default=None, alias="guiaPartidaRuc")
    guia_partida_cod_local: Optional[Annotated[str, Field(strict=True, max_length=4)]] = Field(default=None, alias="guiaPartidaCodLocal")
    guia_partida_geo: Optional[SendDespatchRequestGuiaLlegadaGeo] = Field(default=None, alias="guiaPartidaGeo")
    guia_llegada_ruc: Optional[Annotated[str, Field(min_length=11, strict=True, max_length=11)]] = Field(default=None, alias="guiaLlegadaRuc")
    guia_llegada_cod_local: Optional[Annotated[str, Field(strict=True, max_length=4)]] = Field(default=None, alias="guiaLlegadaCodLocal")
    guia_llegada_geo: Optional[SendDespatchRequestGuiaLlegadaGeo] = Field(default=None, alias="guiaLlegadaGeo")
    documentos_relacionados: Optional[Annotated[List[SendDespatchRequestDocumentosRelacionadosInner], Field(max_length=20)]] = Field(default=None, alias="documentosRelacionados")
    remitente_autorizacion: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, alias="remitenteAutorizacion")
    remitente_autorizacion_entidad: Optional[Annotated[str, Field(strict=True, max_length=2)]] = Field(default=None, alias="remitenteAutorizacionEntidad")
    proveedor_tipo_doc: Optional[Annotated[str, Field(strict=True, max_length=1)]] = Field(default=None, alias="proveedorTipoDoc")
    proveedor_num_doc: Optional[Annotated[str, Field(strict=True, max_length=20)]] = Field(default=None, alias="proveedorNumDoc")
    proveedor_razon_social: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, alias="proveedorRazonSocial")
    comprador_tipo_doc: Optional[Annotated[str, Field(strict=True, max_length=1)]] = Field(default=None, alias="compradorTipoDoc")
    comprador_num_doc: Optional[Annotated[str, Field(strict=True, max_length=20)]] = Field(default=None, alias="compradorNumDoc")
    comprador_razon_social: Optional[Annotated[str, Field(strict=True, max_length=255)]] = Field(default=None, alias="compradorRazonSocial")
    puerto_codigo: Optional[Annotated[str, Field(strict=True, max_length=10)]] = Field(default=None, alias="puertoCodigo")
    puerto_nombre: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(default=None, alias="puertoNombre")
    puerto_tipo: Optional[Annotated[str, Field(strict=True, max_length=1)]] = Field(default=None, alias="puertoTipo")
    destinos: Annotated[List[SendDespatchMultiRequestDestinosInner], Field(min_length=1, max_length=50)]
    __properties: ClassVar[List[str]] = ["tipoDoc", "serie", "observacion", "fechaEmision", "empresaRuc", "establecimientoCodigo", "guiaCodTraslado", "guiaModTraslado", "guiaFecTraslado", "guiaVehiculoPlaca", "transportistaTipoDoc", "transportistaNumDoc", "transportistaRazonSocial", "transportistaNroMtc", "guiaPartidaUbigeo", "guiaPartidaDireccion", "chofer", "guiaFecEntrega", "guiaDesTraslado", "guiaPesoNeto", "guiaSustentoPeso", "guiaNumBultos", "indicadores", "contenedores", "guiaVehiculoTuc", "guiaVehiculoAutorizacion", "guiaVehiculoAutorizacionEntidad", "vehiculosSecundarios", "transportistaAutorizacion", "transportistaAutorizacionEntidad", "guiaPartidaRuc", "guiaPartidaCodLocal", "guiaPartidaGeo", "guiaLlegadaRuc", "guiaLlegadaCodLocal", "guiaLlegadaGeo", "documentosRelacionados", "remitenteAutorizacion", "remitenteAutorizacionEntidad", "proveedorTipoDoc", "proveedorNumDoc", "proveedorRazonSocial", "compradorTipoDoc", "compradorNumDoc", "compradorRazonSocial", "puertoCodigo", "puertoNombre", "puertoTipo", "destinos"]

    @field_validator('tipo_doc')
    def tipo_doc_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['09']):
            raise ValueError("must be one of enum values ('09')")
        return value

    @field_validator('serie', mode="before")
    def serie_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^[A-Z0-9]{4}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Z0-9]{4}$/")
        return value

    @field_validator('establecimiento_codigo', mode="before")
    def establecimiento_codigo_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^\d{4}$", value):
            raise ValueError(r"must validate the regular expression /^\d{4}$/")
        return value

    @field_validator('guia_mod_traslado')
    def guia_mod_traslado_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['01', '02']):
            raise ValueError("must be one of enum values ('01', '02')")
        return value

    @field_validator('transportista_nro_mtc', mode="before")
    def transportista_nro_mtc_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^[A-Z0-9]{1,20}$", value):
            raise ValueError(r"must validate the regular expression /^[A-Z0-9]{1,20}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SendDespatchMultiRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in chofer (list)
        _items = []
        if self.chofer:
            for _item_chofer in self.chofer:
                _items.append(_item_chofer.to_dict() if _item_chofer is not None else None)
            _dict['chofer'] = _items
        # override the default output from pydantic by calling `to_dict()` of indicadores
        if self.indicadores:
            _dict['indicadores'] = self.indicadores.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in contenedores (list)
        _items = []
        if self.contenedores:
            for _item_contenedores in self.contenedores:
                _items.append(_item_contenedores.to_dict() if _item_contenedores is not None else None)
            _dict['contenedores'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in vehiculos_secundarios (list)
        _items = []
        if self.vehiculos_secundarios:
            for _item_vehiculos_secundarios in self.vehiculos_secundarios:
                _items.append(_item_vehiculos_secundarios.to_dict() if _item_vehiculos_secundarios is not None else None)
            _dict['vehiculosSecundarios'] = _items
        # override the default output from pydantic by calling `to_dict()` of guia_partida_geo
        if self.guia_partida_geo:
            _dict['guiaPartidaGeo'] = self.guia_partida_geo.to_dict()
        # override the default output from pydantic by calling `to_dict()` of guia_llegada_geo
        if self.guia_llegada_geo:
            _dict['guiaLlegadaGeo'] = self.guia_llegada_geo.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in documentos_relacionados (list)
        _items = []
        if self.documentos_relacionados:
            for _item_documentos_relacionados in self.documentos_relacionados:
                _items.append(_item_documentos_relacionados.to_dict() if _item_documentos_relacionados is not None else None)
            _dict['documentosRelacionados'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in destinos (list)
        _items = []
        if self.destinos:
            for _item_destinos in self.destinos:
                _items.append(_item_destinos.to_dict() if _item_destinos is not None else None)
            _dict['destinos'] = _items
        # set to None if fecha_emision (nullable) is None
        # and model_fields_set contains the field
        if self.fecha_emision is None and "fecha_emision" in self.model_fields_set:
            _dict['fechaEmision'] = None

        # set to None if guia_fec_traslado (nullable) is None
        # and model_fields_set contains the field
        if self.guia_fec_traslado is None and "guia_fec_traslado" in self.model_fields_set:
            _dict['guiaFecTraslado'] = None

        # set to None if transportista_tipo_doc (nullable) is None
        # and model_fields_set contains the field
        if self.transportista_tipo_doc is None and "transportista_tipo_doc" in self.model_fields_set:
            _dict['transportistaTipoDoc'] = None

        # set to None if transportista_num_doc (nullable) is None
        # and model_fields_set contains the field
        if self.transportista_num_doc is None and "transportista_num_doc" in self.model_fields_set:
            _dict['transportistaNumDoc'] = None

        # set to None if transportista_razon_social (nullable) is None
        # and model_fields_set contains the field
        if self.transportista_razon_social is None and "transportista_razon_social" in self.model_fields_set:
            _dict['transportistaRazonSocial'] = None

        # set to None if guia_fec_entrega (nullable) is None
        # and model_fields_set contains the field
        if self.guia_fec_entrega is None and "guia_fec_entrega" in self.model_fields_set:
            _dict['guiaFecEntrega'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SendDespatchMultiRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tipoDoc": obj.get("tipoDoc"),
            "serie": obj.get("serie"),
            "observacion": obj.get("observacion"),
            "fechaEmision": obj.get("fechaEmision"),
            "empresaRuc": obj.get("empresaRuc"),
            "establecimientoCodigo": obj.get("establecimientoCodigo") if obj.get("establecimientoCodigo") is not None else '0000',
            "guiaCodTraslado": obj.get("guiaCodTraslado"),
            "guiaModTraslado": obj.get("guiaModTraslado"),
            "guiaFecTraslado": obj.get("guiaFecTraslado"),
            "guiaVehiculoPlaca": obj.get("guiaVehiculoPlaca"),
            "transportistaTipoDoc": obj.get("transportistaTipoDoc"),
            "transportistaNumDoc": obj.get("transportistaNumDoc"),
            "transportistaRazonSocial": obj.get("transportistaRazonSocial"),
            "transportistaNroMtc": obj.get("transportistaNroMtc"),
            "guiaPartidaUbigeo": obj.get("guiaPartidaUbigeo"),
            "guiaPartidaDireccion": obj.get("guiaPartidaDireccion"),
            "chofer": [SendDespatchRequestChoferInner.from_dict(_item) for _item in obj["chofer"]] if obj.get("chofer") is not None else None,
            "guiaFecEntrega": obj.get("guiaFecEntrega"),
            "guiaDesTraslado": obj.get("guiaDesTraslado"),
            "guiaPesoNeto": obj.get("guiaPesoNeto"),
            "guiaSustentoPeso": obj.get("guiaSustentoPeso"),
            "guiaNumBultos": obj.get("guiaNumBultos"),
            "indicadores": SendDespatchRequestIndicadores.from_dict(obj["indicadores"]) if obj.get("indicadores") is not None else None,
            "contenedores": [SendDespatchRequestContenedoresInner.from_dict(_item) for _item in obj["contenedores"]] if obj.get("contenedores") is not None else None,
            "guiaVehiculoTuc": obj.get("guiaVehiculoTuc"),
            "guiaVehiculoAutorizacion": obj.get("guiaVehiculoAutorizacion"),
            "guiaVehiculoAutorizacionEntidad": obj.get("guiaVehiculoAutorizacionEntidad"),
            "vehiculosSecundarios": [SendDespatchRequestVehiculosSecundariosInner.from_dict(_item) for _item in obj["vehiculosSecundarios"]] if obj.get("vehiculosSecundarios") is not None else None,
            "transportistaAutorizacion": obj.get("transportistaAutorizacion"),
            "transportistaAutorizacionEntidad": obj.get("transportistaAutorizacionEntidad"),
            "guiaPartidaRuc": obj.get("guiaPartidaRuc"),
            "guiaPartidaCodLocal": obj.get("guiaPartidaCodLocal"),
            "guiaPartidaGeo": SendDespatchRequestGuiaLlegadaGeo.from_dict(obj["guiaPartidaGeo"]) if obj.get("guiaPartidaGeo") is not None else None,
            "guiaLlegadaRuc": obj.get("guiaLlegadaRuc"),
            "guiaLlegadaCodLocal": obj.get("guiaLlegadaCodLocal"),
            "guiaLlegadaGeo": SendDespatchRequestGuiaLlegadaGeo.from_dict(obj["guiaLlegadaGeo"]) if obj.get("guiaLlegadaGeo") is not None else None,
            "documentosRelacionados": [SendDespatchRequestDocumentosRelacionadosInner.from_dict(_item) for _item in obj["documentosRelacionados"]] if obj.get("documentosRelacionados") is not None else None,
            "remitenteAutorizacion": obj.get("remitenteAutorizacion"),
            "remitenteAutorizacionEntidad": obj.get("remitenteAutorizacionEntidad"),
            "proveedorTipoDoc": obj.get("proveedorTipoDoc"),
            "proveedorNumDoc": obj.get("proveedorNumDoc"),
            "proveedorRazonSocial": obj.get("proveedorRazonSocial"),
            "compradorTipoDoc": obj.get("compradorTipoDoc"),
            "compradorNumDoc": obj.get("compradorNumDoc"),
            "compradorRazonSocial": obj.get("compradorRazonSocial"),
            "puertoCodigo": obj.get("puertoCodigo"),
            "puertoNombre": obj.get("puertoNombre"),
            "puertoTipo": obj.get("puertoTipo"),
            "destinos": [SendDespatchMultiRequestDestinosInner.from_dict(_item) for _item in obj["destinos"]] if obj.get("destinos") is not None else None
        })
        return _obj


