# coding: utf-8

"""
    API de Facturación Electrónica SUNAT

    API REST para emisión de comprobantes electrónicos ante SUNAT Perú (Facturas, Boletas, Notas, Guías de Remisión, Resúmenes).

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SendInvoiceRequestDetalleInner(BaseModel):
    """
    SendInvoiceRequestDetalleInner
    """ # noqa: E501
    unidad: Annotated[str, Field(min_length=1, strict=True, max_length=20)]
    cantidad: Union[Annotated[float, Field(strict=True, gt=0)], Annotated[int, Field(strict=True, gt=0)]]
    cod_producto: Annotated[str, Field(min_length=1, strict=True, max_length=50)] = Field(alias="codProducto")
    descripcion: Annotated[str, Field(min_length=1, strict=True, max_length=500)]
    marca: Optional[Annotated[str, Field(strict=True, max_length=100)]] = None
    monto_valor_unitario: Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]] = Field(alias="montoValorUnitario")
    monto_base_igv: Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]] = Field(alias="montoBaseIgv")
    porcentaje_igv: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=18, alias="porcentajeIgv")
    igv: Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]
    tip_afe_igv: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=2)]] = Field(default='10', alias="tipAfeIgv")
    total_impuestos: Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]] = Field(alias="totalImpuestos")
    monto_precio_unitario: Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]] = Field(alias="montoPrecioUnitario")
    monto_valor_venta: Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]] = Field(alias="montoValorVenta")
    descuento: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = None
    descuento_item: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, alias="descuentoItem")
    factor_icbper: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=0, alias="factorIcbper")
    cod_prod_sunat: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, alias="codProdSunat")
    __properties: ClassVar[List[str]] = ["unidad", "cantidad", "codProducto", "descripcion", "marca", "montoValorUnitario", "montoBaseIgv", "porcentajeIgv", "igv", "tipAfeIgv", "totalImpuestos", "montoPrecioUnitario", "montoValorVenta", "descuento", "descuentoItem", "factorIcbper", "codProdSunat"]

    @field_validator('cod_prod_sunat', mode="before")
    def cod_prod_sunat_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^\d{8}$", value):
            raise ValueError(r"must validate the regular expression /^\d{8}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SendInvoiceRequestDetalleInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SendInvoiceRequestDetalleInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "unidad": obj.get("unidad"),
            "cantidad": obj.get("cantidad"),
            "codProducto": obj.get("codProducto"),
            "descripcion": obj.get("descripcion"),
            "marca": obj.get("marca"),
            "montoValorUnitario": obj.get("montoValorUnitario"),
            "montoBaseIgv": obj.get("montoBaseIgv"),
            "porcentajeIgv": obj.get("porcentajeIgv") if obj.get("porcentajeIgv") is not None else 18,
            "igv": obj.get("igv"),
            "tipAfeIgv": obj.get("tipAfeIgv") if obj.get("tipAfeIgv") is not None else '10',
            "totalImpuestos": obj.get("totalImpuestos"),
            "montoPrecioUnitario": obj.get("montoPrecioUnitario"),
            "montoValorVenta": obj.get("montoValorVenta"),
            "descuento": obj.get("descuento"),
            "descuentoItem": obj.get("descuentoItem"),
            "factorIcbper": obj.get("factorIcbper") if obj.get("factorIcbper") is not None else 0,
            "codProdSunat": obj.get("codProdSunat")
        })
        return _obj


